function data=load_dataBTS_markers(filename)


%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/Nevio 1/Lavoro/Part B/UCBM/Didattica/Didattica RTDA/Laboratorio di Bioingegneria/2020-2021/Esercitazioni/3 Esercitazione statica/materiale esercitazione/data_20-21/TurnoA/walking3_turnoA_traccePunti.txt
%
% To extend the code to different selected data or a different text file, generate a function instead of a script.

% Auto-generated by MATLAB on 2021/05/18 06:31:15

%% Initialize variables.

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%7s%7s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%11s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38]
    % Converts text in the input cell array to numbers. Replaced non-numeric text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
Frame = cell2mat(raw(:, 1));
Time = cell2mat(raw(:, 2));
rAsisX = cell2mat(raw(:, 3));
rAsisY = cell2mat(raw(:, 4));
rAsisZ = cell2mat(raw(:, 5));
rThighX = cell2mat(raw(:, 6));
rThighY = cell2mat(raw(:, 7));
rThighZ = cell2mat(raw(:, 8));
rKnee1X = cell2mat(raw(:, 9));
rKnee1Y = cell2mat(raw(:, 10));
rKnee1Z = cell2mat(raw(:, 11));
rMallX = cell2mat(raw(:, 12));
rMallY = cell2mat(raw(:, 13));
rMallZ = cell2mat(raw(:, 14));
rMetX = cell2mat(raw(:, 15));
rMetY = cell2mat(raw(:, 16));
rMetZ = cell2mat(raw(:, 17));
lAsisX = cell2mat(raw(:, 18));
lAsisY = cell2mat(raw(:, 19));
lAsisZ = cell2mat(raw(:, 20));
lThighX = cell2mat(raw(:, 21));
lThighY = cell2mat(raw(:, 22));
lThighZ = cell2mat(raw(:, 23));
lKnee1X = cell2mat(raw(:, 24));
lKnee1Y = cell2mat(raw(:, 25));
lKnee1Z = cell2mat(raw(:, 26));
lMallX = cell2mat(raw(:, 27));
lMallY = cell2mat(raw(:, 28));
lMallZ = cell2mat(raw(:, 29));
lMetX = cell2mat(raw(:, 30));
lMetY = cell2mat(raw(:, 31));
lMetZ = cell2mat(raw(:, 32));
rHeelX = cell2mat(raw(:, 33));
rHeelY = cell2mat(raw(:, 34));
rHeelZ = cell2mat(raw(:, 35));
lHeelX = cell2mat(raw(:, 36));
lHeelY = cell2mat(raw(:, 37));
lHeelZ = cell2mat(raw(:, 38));


%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp R;


data.RGT(:,1)=rThighX;
data.RGT(:,2)=rThighY;
data.RGT(:,3)=rThighZ;

data.LGT(:,1)=lThighX;
data.LGT(:,2)=lThighY;
data.LGT(:,3)=lThighZ;

data.RLE(:,1)=rKnee1X;
data.RLE(:,2)=rKnee1Y;
data.RLE(:,3)=rKnee1Z;

data.LLE(:,1)=lKnee1X;
data.LLE(:,2)=lKnee1Y;
data.LLE(:,3)=lKnee1Z;

data.RLM(:,1)=rMallX;
data.RLM(:,2)=rMallY;
data.RLM(:,3)=rMallZ;

data.LLM(:,1)=lMallX;
data.LLM(:,2)=lMallY;
data.LLM(:,3)=lMallZ;

data.RVM(:,1)=rMetX;
data.RVM(:,2)=rMetY;
data.RVM(:,3)=rMetZ;

data.LVM(:,1)=lMetX;
data.LVM(:,2)=lMetY;
data.LVM(:,3)=lMetZ;

data.RASIS(:,1)=rAsisX;
data.RASIS(:,2)=rAsisY;
data.RASIS(:,3)=rAsisZ;

data.LASIS(:,1)=lAsisX;
data.LASIS(:,2)=lAsisY;
data.LASIS(:,3)=lAsisZ;


end